apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthquake
  namespace: earthquake
spec:
  selector:
    matchLabels:
      app: earthquake
  replicas: 2
  template:
    metadata:
      labels:
        app: earthquake
    spec:
      containers:
      - name: earthquake
        image: yumekiti/earthquake:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earthquake
  namespace: earthquake
spec:
  selector:
    app: earthquake
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: earthquake
  namespace: earthquake
spec:
  ingressClassName: nginx
  rules:
  - host: earthquake.yumekiti.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: earthquake
            port:
              number: 80